# Generated by Django 5.1.4 on 2025-01-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_owner_car_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceRecord',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='series',
        ),
        migrations.RemoveField(
            model_name='car',
            name='license_plate',
        ),
    ]
